webclient:
  max-connect: 10
  connection-timeout: 5000
  response-timeout: 5000
  read-timeout: 5000
  write-timeout: 5000

ipAddress:
  base-url: http://ip.jsontest.com

slack:
  base-url: https://slack.com/api/chat.postMessage
  bearer-token: 토큰토큰
  channel: bot-error
  username: ErrorBot

kakao:
  base-url: https://kauth.kakao.com/oauth/token
  client-id: 토큰토큰
  redirect-uri: http://localhost:3000/login/kakao